// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXStU7FsNgn0Z3a3o9mf10VI2u9UahPR8',
    appId: '1:738929725254:web:b74f3cad4c0acbdee3df47',
    messagingSenderId: '738929725254',
    projectId: 'restarauntapp-c88f7',
    authDomain: 'restarauntapp-c88f7.firebaseapp.com',
    databaseURL: 'https://restarauntapp-c88f7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'restarauntapp-c88f7.appspot.com',
    measurementId: 'G-XS4NRVQLN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjtRmAZJyEmG_RzJR6i_W-N8WhqGpmTBY',
    appId: '1:738929725254:android:747b0cc2d91d3893e3df47',
    messagingSenderId: '738929725254',
    projectId: 'restarauntapp-c88f7',
    databaseURL: 'https://restarauntapp-c88f7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'restarauntapp-c88f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMdH91k0hrrouROGarzI_Mz2aqGb2AGJA',
    appId: '1:738929725254:ios:d0feb4cd17a3d730e3df47',
    messagingSenderId: '738929725254',
    projectId: 'restarauntapp-c88f7',
    databaseURL: 'https://restarauntapp-c88f7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'restarauntapp-c88f7.appspot.com',
    iosClientId: '738929725254-d3v0kprg02iuimajsq2550rensjt0eg3.apps.googleusercontent.com',
    iosBundleId: 'com.example.restarauntApp',
  );
}
